apiVersion: apps/v1 
kind: Deployment
metadata:
  name: pdsdemo-v1
  namespace: pdsplayground
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: pds-container
        image: sultanss/pdsdemotag1
        ports: 
          - containerPort: 3001