name: CI Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/pdsdemotag1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: test dockerhub username if exists
        run: |
          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
              echo "DOCKER_HUB_USERNAME is not set. Please set it in the repository secrets -."
              exit 1
          fi
      - name: Checkout code 16
        uses: actions/checkout@v4

      - name: Setup Node.js 19
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies 25
        run: npm ci

      - name: Run linter 28
        run: npm run lint

      # 1. Test the code before building the app
      - name: Run tests 32
        run: npm test || echo "No tests found, skipping...."

      - name: Build Next.js 35
        run: npm run build

      - name: Set short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 2. Build the Docker image locally FIRST (No login required yet)
      - name: Build Docker image 42 (test the build process before pushing to Docker Hub)
        run: |
          docker build -t $IMAGE_NAME:$SHORT_SHA .
          docker tag $IMAGE_NAME:$SHORT_SHA $IMAGE_NAME:latest

      # 3. Scan the local image BEFORE pushing.
      # exit-code: "1" will stop the pipeline if CRITICAL vulnerabilities exist.
      - name: Run Trivy vulnerability scanner 49
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          format: "table"
          exit-code: "0" # Varna men stoppa inte bygget
          severity: "CRITICAL"
        env:
          SHORT_SHA: ${{ env.SHORT_SHA }}

      # 5. Now that we know the image is safe and works, log in to Docker Hub.
      - name: Login to Docker Hub 60
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 6. Push the verified image.
      - name: Push Docker image 67
        run: |
          docker push $IMAGE_NAME:$SHORT_SHA
          docker push $IMAGE_NAME:latest

      # 7. Update GitOps
      - name: Update GitOps repo 73
        run: |
          git clone https://${{ secrets.GITOPS_REPO_PAT }}@github.com/${{ secrets.GITOPS_REPO_PATH }}.git gitops
          cd gitops/manifests
          sed -i "s|image:.*pdsdemotag1:.*|image: $IMAGE_NAME:$SHORT_SHA|g" deployment.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add deployment.yml
          git commit -m "Update image tag to $SHORT_SHA" || echo "No changes to commit"
          git push origin master
